# Generated by Django 3.2.16 on 2023-01-09 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 9, 23, 39, 13, 328256)),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=50),
        ),
    ]
