# Generated by Django 3.2.13 on 2023-01-10 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_app', '0005_auto_20230110_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 12, 33, 33, 50789)),
        ),
        migrations.AlterField(
            model_name='token',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 12, 33, 33, 49792)),
        ),
    ]
